export { default as Header } from './header'
// export { default as Footer } from './footer'
export { default as Sider } from './sider'
export { default as BreadCrumb } from './breadCrumb/index'
export { default as OrdersTable } from './ordersTable'
export { default as OrderHeader } from './orderHeader'
export { default as OrdersHeader } from './ordersHeader'
export { default as ProductHeader } from './productHeader'
export { default as SttHeader } from './statisticHeader'
export { default as Notification } from './notification'

